### ISSUE TITLE
Celluoid 0.16.1 has been yanked

### ISSUE THREAD

**Issue by tmartin314** [brandonhilkert/sucker_punch#122]
May need to update to version 0.17.0

https://rubygems.org/gems/celluloid/versions

**Comment by derrek** [comment]
:+1:  just ran into this mess.  Had to add celluloid fixed at 0.16.0 into the Gemfile to satisfy sucker_punch dependencies and bundle without error.

**Comment by brandonhilkert** [comment]
Unfortunately, this is a little more complicated, b/c the pools that were used were split out. I wish i could update it real quick, but it's going to take more refactoring to implement the new release. Sorry :/

**Comment by brandonhilkert** [comment]
It doesn't look yanked anymore, can you confirm there's still an issue. I can lock it at `0.16.0` if that would help now. Thoughts?

**Comment by derrek** [comment]
I think it's still yanked. If I go here: https://rubygems.org/gems/celluloid/versions i see
```
0.16.1 - August 8, 2015 (63.5 KB) yanked
```

**Comment by brandonhilkert** [comment]
@derrek I see, but 0.16.0 is still out. So if i lock to that, would that solve the problem for now? it's the using optimistic versioning so the trouble is when you already have `0.16.1` installed on your system.

**Comment by brandonhilkert** [comment]
Just released version `1.5.1` of Sucker Punch locked to the lower version. Please confirm if that fixed it for now.

**Comment by derrek** [comment]
Looks good :+1:
